<!-- to start this on a new page -->
\clearpage

**PhD candidate:** François Leroy\newline
**Programme:** Environmental Earth Sciences\newline
**Department:** [Spatial Sciences](https://www.fzp.czu.cz/en/r-9407-departments/r-9471-departments/r-9649-department-of-spatial-sciences)\newline
**Advisor:** [doc. Ing. Petra Šímová, Ph.D.](http://wp.czu.cz/cs/index.php/?r=1071&mp=person.info&idClovek=2155)\newline
**Consultant:** Mgr. [Petr Keil](http://wp.czu.cz/cs/index.php/?r=1071&mp=person.info&idClovek=34772), PhD\newline
**Beginning of study:** October 2020\newline
\newline

<!-- The new group is the only the introduction for it to start just after my specififcations-->
\begingroup
\let\clearpage\relax

# Introduction {#intro}


Human life quality is intrinsically linked to ecosystems state that he is living in. Indeed, ecosystems services extend in a large spectrum of mechanisms including nutrient cycle, food production, or climate and water cycle regulation [@pereira_global_2012]. Some of those ecosystem
functions are managed by bird populations such as seed dispersal, controls pests or pollinate plant.
Unfortunately, anthropogenic stressors like habitat loss, over exploitation, pollution or introduction of
invasive species could lead biodiversity to its sixth mass extinction [@barnosky_has_2011].


While the loss of global biodiversity is unprecedented, current scientific literature has also shown that
temporal trends in local changes of biodiversity can be opposite to trends at larger scales [@chase_species_2019]. Thus, current changes in biodiversity is far more complex than a simple global decrease:
most of the ecosystems undergo alterations of their communities with changes in species composition [@blowes_geography_2019; @dornelas_assemblage_2014]. 


Typically, biodiversity is considered for a particular taxon (*e.g.* birds, amphibians, reptiles...), but also
according to the spatial scale it is defined by. Here, the term scale refers to the area in which the
biodiversity in considered, also referred hereafter as grain size. So far, it has been assumed that
holding the spatial scale constant when studying biodiversity is mandatory [@whittaker_scale_2001]. As
a matter of fact, it is known that species richness increases with the area considered [@arrhenius_species_1921] and this relationship is approximately linear on a log-log scale (Species-Area Relationship,
SAR). However, this assumption restricts the data accessibility as sampling plans widely differ
according to the species studied, the resources available or, the field conditions. Thus, developing a
method capable of dealing with biodiversity across varying grain size could increase significantly the
data availability. Moreover, it would allow to model biodiversity at different spatial scales than the
ones used in the data. Modelling biodiversity indexes at finer spatial grain size that the data used to
learn the model is referred as *downscaling* biodiversity whilst extrapolating at coarser grain-size is
called *upscaling*.

So far, there are indications that such method can be used. For instance, @keil_downscaling_2014 and @keil_downscaling_2013 showed promising downscaling biodiversity models using biodiversity data with different
spatial scales, whilst @kunin_upscaling_2018 showed that upscaling biodiversity is also possible. Thus, all
the constituents of cross-scales models are known but still need to be gathered and tested. For
instance, @jarzyna_spatial_2015 used a Bayesian framework to study temporal changes of avian
biodiversity (colonization, extinction, temporal turnover) across scales. However, other approaches
such as parametric Generalized Linear Models (GLM), Generalized Additive Models (GAM) and
Generalized Linear Mixed Model (GLMM) or non-parametric tree based machine learning methods
need to be tested.

\endgroup
